In [54]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("uber dataset.csv")

In [32]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  object
 2   tpep_dropoff_datetime  100000 non-null  object
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  object
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: float64(12), int64(4), object(3)
memory usage: 14.5+ MB

# Data Cleaning

In [34]:
# Converting data type of date variables into datetime data type
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

In [35]:
# Dropping duplicates in all column variables if exist
df = df.drop_duplicates().reset_index(drop=True)  # 'reset_index(drop=True)' resets the row index back to a default 0-based sequential index and drop the existying indexing 
df['trip_id'] = df.index

In [36]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,trip_id
0,1,2016-03-01,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35,0
1,1,2016-03-01,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35,1
2,2,2016-03-01,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80,2
3,2,2016-03-01,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62,3
4,2,2016-03-01,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80,4

# Data Transformation

## Creating the Dimension Tables

No Dimension tables are created for the columns 'store_and_fwd_flag' and 'vendor_id' because the columns do not contribute to the purpose of the analysis, so they are not included in the Data Model.

Removing duplicates at the column level:

* Dropping duplicates at the main table "df" level only removes duplicated FULL rows and not specific to the mentioned column/key.


* Dropping duplicates (.drop_duplicates() ) is done when creating each dimension table. This ensures that duplicated rows with regards to the specific column/key are removed.

#### "datetime_dim" table

In [37]:
# Creating the dimension table "datetime_dim"
datetime_dim = df[['tpep_pickup_datetime','tpep_dropoff_datetime']].drop_duplicates().reset_index(drop=True)

# Creating pickup date/time columns using the "datetime_dim" table
datetime_dim['pickup_hour'] =  datetime_dim['tpep_pickup_datetime'].dt.hour  # creating a pickup hour column
datetime_dim['pickup_day'] =  datetime_dim['tpep_pickup_datetime'].dt.day  # creating a pickup day column
datetime_dim['pickup_month'] =  datetime_dim['tpep_pickup_datetime'].dt.month  # creating a pickup month column
datetime_dim['pickup_year'] =  datetime_dim['tpep_pickup_datetime'].dt.year  # creating a pickup year column
datetime_dim['pickup_weekday'] =  datetime_dim['tpep_pickup_datetime'].dt.weekday  # creating a pickup weekday column


# Creating dropoff date/time columns using the "datetime_dim" table
datetime_dim['dropoff_hour'] =  datetime_dim['tpep_dropoff_datetime'].dt.hour  # creating a dropoff hour column
datetime_dim['dropoff_day'] =  datetime_dim['tpep_dropoff_datetime'].dt.day  # creating a dropoff day column
datetime_dim['dropoff_month'] =  datetime_dim['tpep_dropoff_datetime'].dt.month  # creating a dropoff month column
datetime_dim['dropoff_year'] =  datetime_dim['tpep_dropoff_datetime'].dt.year  # creating a dropoff year column
datetime_dim['dropoff_weekday'] =  datetime_dim['tpep_dropoff_datetime'].dt.weekday  # creating a dropoff weekday column

# Creating a column to represent the row index values in the "datetime_dim" table
datetime_dim['datetime_id'] = datetime_dim.index

# Sorting the columns in sequence
datetime_dim = datetime_dim[['datetime_id', 'tpep_pickup_datetime', 'pickup_hour', 'pickup_day', 'pickup_month', 'pickup_year', 'pickup_weekday',
                             'tpep_dropoff_datetime', 'dropoff_hour', 'dropoff_day', 'dropoff_month', 'dropoff_year', 'dropoff_weekday']]

datetime_dim.head()

,datetime_id,tpep_pickup_datetime,pickup_hour,pickup_day,pickup_month,pickup_year,pickup_weekday,tpep_dropoff_datetime,dropoff_hour,dropoff_day,dropoff_month,dropoff_year,dropoff_weekday
0,0,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:07:55,0,1,3,2016,1
1,1,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:11:06,0,1,3,2016,1
2,2,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:31:06,0,1,3,2016,1
3,3,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1
4,4,2016-03-01 00:00:01,0,1,3,2016,1,2016-03-01 00:16:04,0,1,3,2016,1

#### "passenger_count_dim" table

In [38]:
# Creating the dimension table "passenger_count_dim" by extracting the 'passenger_count' column from the dataset
passenger_count_dim = df[['passenger_count']].drop_duplicates().reset_index(drop=True)  # double[] because we are extracting out as a dataframe (dimension tables are 2D format)

# Creating an indexing column
passenger_count_dim['passenger_count_id'] = passenger_count_dim.index # single[] because each column in a dataframe is a Series, we are creating a single column so use single[]

# Sorting the columns in sequence
passenger_count_dim = passenger_count_dim[['passenger_count_id','passenger_count']]

passenger_count_dim.head()

   passenger_count_id  passenger_count
0                   0                1
1                   1                2
2                   2                3
3                   3                5
4                   4                6

#### "trip_distance_dim" table

In [39]:
# Creating the dimension table "trip_distance_dim" by extracting the 'trip_distance' column from the dataset and resetting the indexing to start from 0 in sequence
trip_distance_dim = df[['trip_distance']].drop_duplicates().reset_index(drop=True)

# Use the new sequential index and assigns a name to the index column
trip_distance_dim['trip_distance_id'] = trip_distance_dim.index 

# Sorting the sequence of columns
trip_distance_dim = trip_distance_dim[['trip_distance_id','trip_distance']]
trip_distance_dim.head()

   trip_distance_id  trip_distance
0                 0           2.50
1                 1           2.90
2                 2          19.98
3                 3          10.78
4                 4          30.43

#### "rate_code_dim" table

In [40]:
rate_code_type = {
    1:"Standard rate",
    2:"JFK",
    3:"Newark",
    4:"Nassau or Westchester",
    5:"Negotiated fare",
    6:"Group ride"
}
 
# create new dataframe from extracting 'RatecodeID' column from the original dataset and resetting the indexing to start from 0 sequentially
rate_code_dim = df[['RatecodeID']].drop_duplicates().reset_index(drop=True)  

# uses the new sequential index and assigns a name to the index column
rate_code_dim['rate_code_id'] = rate_code_dim.index  

# creating a new column to map names to the values in the 'RatecodeID' column
rate_code_dim['rate_code_name'] = rate_code_dim['RatecodeID'].map(rate_code_type)

# Sorting the sequence of columns
rate_code_dim = rate_code_dim[['rate_code_id','RatecodeID','rate_code_name']]

rate_code_dim.head()

   rate_code_id  RatecodeID         rate_code_name
0             0           1          Standard rate
1             1           3                 Newark
2             2           2                    JFK
3             3           5        Negotiated fare
4             4           4  Nassau or Westchester

#### "pickup_location_dim" table

In [41]:
# create new dataframe by extracting the pickup longitude and latitude columns from the original dataset and resetting index to start from 0 sequentially 
pickup_location_dim = df[['pickup_longitude','pickup_latitude']].drop_duplicates().reset_index(drop=True)

# use the new sequential index and assign a new coulmn header to the column index
pickup_location_dim['pickup_location_id'] = pickup_location_dim.index

# sorting the columns in sequence
pickup_location_dim = pickup_location_dim[['pickup_location_id','pickup_latitude','pickup_longitude']]
pickup_location_dim.head()

   pickup_location_id  pickup_latitude  pickup_longitude
0                   0        40.765152        -73.976746
1                   1        40.767925        -73.983482
2                   2        40.644810        -73.782021
3                   3        40.769814        -73.863419
4                   4        40.792183        -73.971741

#### "dropoff_location_dim" table

In [42]:
# create new dataframe by extracting the dropoff longitude and latitude columns from the original dataset and resetting index to start from 0 sequentially 
dropoff_location_dim = df[['dropoff_longitude','dropoff_latitude']].drop_duplicates().reset_index(drop=True)

# use the new sequential index and assign a new coulmn header to the column index
dropoff_location_dim['dropoff_location_id'] = dropoff_location_dim.index

# sorting the columns in sequence
dropoff_location_dim = dropoff_location_dim[['dropoff_location_id','dropoff_latitude','dropoff_longitude']]
dropoff_location_dim.head()

   dropoff_location_id  dropoff_latitude  dropoff_longitude
0                    0         40.746128         -74.004265
1                    1         40.733166         -74.005943
2                    2         40.675770         -73.974541
3                    3         40.757767         -73.969650
4                    4         40.695053         -74.177170

#### "payment_type_dim" table

In [43]:
payment_type_name = {
    1:"Credit card",
    2:"Cash",
    3:"No charge",
    4:"Dispute",
    5:"Unknown",
    6:"Voided trip"
}

# creating new dataframe/table by extracting the column 'payment_type' from the original dataset and resetting the indexing to start from 0 sequentially
payment_type_dim = df[['payment_type']].drop_duplicates().reset_index(drop=True)

# use the newly resetted sequential index and assign a new column name
payment_type_dim['payment_type_id'] = payment_type_dim.index

# map the original numerical values in column 'payment_type' to actual label names under a newly created column
payment_type_dim['payment_type_name'] = payment_type_dim['payment_type'].map(payment_type_name)

# sorting the columns in sequence
payment_type_dim = payment_type_dim[['payment_type_id','payment_type_name','payment_type']]
payment_type_dim.head()

   payment_type_id payment_type_name  payment_type
0                0       Credit card             1
1                1              Cash             2
2                2         No charge             3
3                3           Dispute             4

## Verifying no more duplicated rows in Dimension Tables

In [50]:
print("dropoff_location_dim duplicates:", dropoff_location_dim.duplicated(['dropoff_longitude', 'dropoff_latitude']).sum())
print("datetime_dim duplicates:", datetime_dim.duplicated(['tpep_pickup_datetime', 'tpep_dropoff_datetime']).sum())
print("payment_type_dim duplicates:", payment_type_dim.duplicated(['payment_type']).sum())
print("pickup_location_dim duplicates:", pickup_location_dim.duplicated(['pickup_longitude','pickup_latitude']).sum())
print("rate_code_dim duplicates:", rate_code_dim.duplicated(['RatecodeID']).sum())
print("trip_distance_dim duplicates:", trip_distance_dim.duplicated(['trip_distance']).sum())
print("passenger_count_dim duplicates:", passenger_count_dim.duplicated(['passenger_count']).sum())

dropoff_location_dim duplicates: 0
datetime_dim duplicates: 0
payment_type_dim duplicates: 0
pickup_location_dim duplicates: 0
rate_code_dim duplicates: 0
trip_distance_dim duplicates: 0
passenger_count_dim duplicates: 0

## Creating the Fact table

Only quantitative/numerical columns from the DIMENSION tables are included in the FACT table as we are following a Star Schema. (i.e Only keys from the DIMENSION tables that can be represented as foreign keys in the FACT table are pulled e.g ID columns)

In [51]:
# creating the fact table by merging the original dataframe with the individual dimension tables using the common key
fact_table = df.merge(passenger_count_dim, on='passenger_count')\
             .merge(trip_distance_dim, on='trip_distance')\
             .merge(pickup_location_dim, on=['pickup_longitude','pickup_latitude'])\
             .merge(dropoff_location_dim, on=['dropoff_longitude','dropoff_latitude'])\
             .merge(datetime_dim, on=['tpep_pickup_datetime','tpep_dropoff_datetime'])\
             .merge(rate_code_dim, on='RatecodeID')\
             .merge(payment_type_dim, on='payment_type')\
             [['VendorID', 'datetime_id', 'passenger_count_id',
               'trip_distance_id', 'pickup_location_id', 'dropoff_location_id', 'rate_code_id',
               'payment_type_id', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
               'improvement_surcharge', 'total_amount', 'store_and_fwd_flag']]
fact_table

,VendorID,datetime_id,passenger_count_id,trip_distance_id,pickup_location_id,dropoff_location_id,rate_code_id,payment_type_id,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,store_and_fwd_flag
0,1,0,0,0,0,0,0,0,9.0,0.5,0.5,2.05,0.00,0.3,12.35,N
1,1,1,0,1,1,1,0,0,11.0,0.5,0.5,3.05,0.00,0.3,15.35,N
2,2,2,1,2,2,2,0,0,54.5,0.5,0.5,8.00,0.00,0.3,63.80,N
3,2,3,2,3,3,3,0,0,31.5,0.0,0.5,3.78,5.54,0.3,41.62,N
4,2,3,3,4,4,4,1,0,98.0,0.0,0.0,0.00,15.50,0.3,113.80,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1,99848,0,19,98050,98412,0,1,5.0,0.0,0.5,0.00,0.00,0.3,5.80,N
99996,1,99849,0,71,98051,98413,0,0,14.0,0.0,0.5,2.00,0.00,0.3,16.80,N
99997,1,99850,0,295,98052,98414,0,0,29.0,0.0,0.5,8.80,5.54,0.3,44.14,N
99998,2,99851,0,152,98053,98415,0,0,5.5,0.5,0.5,1.36,0.00,0.3,8.16,N
99999,1,99852,0,29,98054,98416,0,1,6.0,0.0,0.5,0.00,0.00,0.3,6.80,N